# This is a basic workflow to help you get started with Actions

name: CI

# Every Sunday at 6:50CT
on:
  schedule:
    - cron: '45 23 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cut release branch
      run: sh ./scripts/release-branch-creator.sh
