on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print goodbye
        run: echo "Goodbye, ${{inputs.username}}"!
