on:
  push

jobs:
  reuse-from-same-repository:
    uses: mrea1/WeatherApp/.github/workflows/reusable.yml@master
    with:
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.JIRA_TOKEN }}
