on:
  push

jobs:
  reuse-from-same-repository:
    uses: mrea1/WeatherApp/.github/workflows/test-reusable.yml@mr-test-reusable-from-another-repo
    with:
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.JIRA_TOKEN }}
